# Generated by Django 3.1.4 on 2020-12-28 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokegutkowo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='discord',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Link do discorda'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='owner_about',
            field=models.TextField(blank=True, null=True, verbose_name='O właścicielu'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='owner_acc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pokegutkowo.player'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='owner_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Screenshot właściciela'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nazwa strony'),
        ),
    ]
